version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.cloud:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springdoc:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "de.codecentric:*"
        update-types: ["version-update:semver-major"]
    groups:
      maven-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 15

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.cloud:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springdoc:*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "de.codecentric:*"
        update-types: ["version-update:semver-major"]
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 15

  - package-ecosystem: "docker"
    directory: "/camila-orchestrator/dev/compose/monitoring/fluentd/"
    schedule:
      interval: "weekly"
    groups:
      infrastructure-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/camila-orchestrator/dev/compose/"
    schedule:
      interval: "weekly"
    groups:
      infrastructure-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "terraform"
    directory: "/camila-orchestrator/pre/aws/terraform/templates/"
    schedule:
      interval: "weekly"
    groups:
      infrastructure-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
