version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "io.opentelemetry.*"
    open-pull-requests-limit: 0

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "docker"
    directory: "/camila-orchestrator/dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "docker-compose"
    directory: "/camila-orchestrator/dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
    open-pull-requests-limit: 0

