version: '3'
services:
  config:
    image: docker.io/library/camila-config:1.0.0
    container_name: camila-config
    environment:
      SPRING_PROFILES_ACTIVE: "dev,native"
      JVM_OPTIONS: "-Xmx256m -Xms1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5045"
      EUREKA_URI: "http://discovery:8761/eureka"
    ports:
      - "5045:5045"
      - "8888:8888"
    expose:
      - 5045
      - 8888
    volumes:
      - camila_config_tmp:/tmp
    networks:
      camila_product_network:
        ipv4_address: 172.18.0.254
  discovery:
    image: docker.io/library/camila-discovery:1.0.0
    container_name: camila-discovery
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      JVM_OPTIONS: "-Xmx256m -Xms1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5025"
    ports:
      - "5025:5025"
      - "8761:8761"
    expose:
      - 5025
      - 8761
    depends_on:
      - "config"
    volumes:
      - camila_discovery_tmp:/tmp
    networks:
      camila_product_network:
  gateway:
    image: docker.io/library/camila-gateway:1.0.0
    container_name: camila-gateway
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      JVM_OPTIONS: "-Xmx256m -Xms1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5015"
      PRODUCT_SERVER_URL: "lb://CAMILA-PRODUCT-API"
      EUREKA_URI: "http://discovery:8761/eureka"
    ports:
      - "5015:5015"
      - "8090:8090"
    expose:
      - 5015
      - 8090
    depends_on:
      - "config"
    volumes:
      - camila_gateway_tmp:/tmp
    networks:
      camila_product_network:
  admin:
    image: docker.io/library/camila-admin:1.0.0
    container_name: camila-admin
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      JVM_OPTIONS: "-Xmx256m -Xms1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5035"
      EUREKA_URI: "http://discovery:8761/eureka"
    ports:
      - "5035:5035"
      - "8100:8100"
    expose:
      - 5035
      - 8100
    depends_on:
      - "discovery"
      - "config"
    volumes:
      - camila_admin_tmp:/tmp
    networks:
      camila_product_network:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: camila-product-db   
    ports: 
      - "27017-27019:27017-27019"
    expose:
      - 27017
      - 27018
      - 27019
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=camila
      - MONGODB_INITDB_ROOT_PASSWORD=camila
    volumes:
      - camila_product_mongodb_data:/data/db
    networks: 
      camila_product_network:
  backend-product:
    image: docker.io/library/camila-product-api:1.0.0
    deploy:
      mode: replicated
      replicas: 3
    environment:
      spring.data.mongodb.uri: "mongodb://camilauser:camilauser@mongodb:27017/camila-db"
      SPRING_PROFILES_ACTIVE: "dev"
      LANG: "en_US.utf8"
      LANGUAGE: "en_US.utf8"
      LC_ALL: "en_US.utf8"
      TIME_ZONE: UTC
      JVM_OPTIONS: "-Xmx512m -Xms1024m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
      EUREKA_URI: "http://discovery:8761/eureka"
    ports:
      - "5005-5007:5005"
      - "8080-8082:8080"
    expose:
      - 5005-5007
      - 8080-8082
    depends_on:
      - "mongodb"
      - "config"
    volumes:
      - camila_product_backend_tmp:/tmp
    networks:
      camila_product_network:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      camila_product_network:
  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
      - "3000:3000"
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - ./monitoring/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    networks:
      camila_product_network:

volumes:
  camila_product_mongodb_data:
  camila_product_backend_tmp:
  camila_gateway_tmp:
  camila_discovery_tmp:
  camila_admin_tmp:
  camila_config_tmp:
  grafana_data:

networks:
  camila_product_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
