# http://localhost:8080/product-dev/api/swagger-ui.html
GET http://localhost:8080/product-dev/api/actuator/health HTTP/2
Accept: application/json
Content-Type: application/json

### Rest - findById (SSE)
GET http://localhost:8080/product-dev/api/products/1 HTTP/2
Accept: text/event-stream
Content-Type: application/json

### Rest - sortProducts (ndjson)
GET http://localhost:8080/product-dev/api/products?salesUnits=0.70&stock=0.20&profitMargin=0.05&daysInStock=0.05&page=0&size=20 HTTP/2
Accept: application/x-ndjson
Content-Type: application/json

### Graphql - findById
GRAPHQL http://localhost:8080/product-dev/api/graphql

query findById($internalId: ID) {
  findById(internalId: $internalId) {
    id, internalId, category, name, salesUnits, stock
  }
}

{
"internalId": "1"
}

### Graphql - sortProducts
GRAPHQL http://localhost:8080/product-dev/api/graphql

query sortProducts($salesUnits: Float, $stock: Float, $profitMargin: Float, $daysInStock: Float, $page: Int, $size: Int, $withDetails: Boolean!) {
  sortProducts(salesUnits: $salesUnits, stock: $stock, profitMargin: $profitMargin, daysInStock: $daysInStock, page: $page, size: $size) {
    id @include(if: $withDetails)
    internalId @include(if: $withDetails)
    category @include(if: $withDetails)
    name
    salesUnits
    stock
    profitMargin
    daysInStock
  }
}

{
  "salesUnits": 0.010,
  "stock": 0.970,
  "profitMargin": 0.010,
  "daysInStock": 0.010,
  "page": 0,
  "size": 2,
  "withDetails": false
}

### Websockt
WEBSOCKET ws://localhost:8080/product-dev/api/ws/products
Content-Type: application/json

===
{
  "method": "FIND_BY_INTERNAL_ID",
  "internalId": "1"
}
=== wait-for-server
{
  "method": "SORT_PRODUCTS",
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "5"
}
=== wait-for-server

### RSocket request rsponse with websocket - findByInternalId
RSOCKET products.request-response-findByInternalId
Host: ws://localhost:7000/product-dev/api/rsocket

{
  "internalId": "5"
}

### RSocket request stream with websocket - SortProducts
RSOCKET products.request-stream-sortByMetricsWeights
Host: ws://localhost:7000/product-dev/api/rsocket

{
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "5"
}

### GRPC - findByInternalId
GRPC localhost:6565/product.ProductService/GetProductByInternalId

{
  "internalId": "1"
}

### GRPC - SortProducts
GRPC localhost:6565/product.ProductService/SortByMetricsWeights

{
  "requestParams": {
    "stock": "1.0",
    "page": "0",
    "size": "10000"
  }
}
