AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to Camila Secrets

Parameters:
  CouchbasePassword:
    Type: String
    Description: The Couchbase password
    NoEcho: true
  MongoUri:
    Type: String
    Description: The MongoDB URI
    NoEcho: true

Resources:
  # Create a couchbase password secret
  # https://aws.amazon.com/es/secrets-manager/pricing/
  # 0.40 $/month
  CouchbasePasswordSecret:
    Type: "AWS::SecretsManager::Secret"
    Description: "Couchbase password"
    DeletionPolicy: Delete
    Properties:
      Name: "CouchbasePassword"
      Description: "Couchbase password"
      SecretString: !Sub '{"password":"${CouchbasePassword}"}'
      Tags:
        - Key: "Name"
          Value: "CouchbasePassword"
        - Key: "ENTORN"
          Value: "PRE"

  # Create a mongo uri secret
  MongoUriSecret:
    Type: "AWS::SecretsManager::Secret"
    Description: "Mongo URI"
    DeletionPolicy: Delete
    Properties:
      Name: "MongoUri"
      Description: "Mongo URI"
      SecretString: !Sub '{"uri":"${MongoUri}"}'
      Tags:
        - Key: "Name"
          Value: "MongoUri"
        - Key: "ENTORN"
          Value: "PRE"

Outputs:
  CouchbasePasswordSecret:
    Description: Couchbase password secret ID
    Value: !Ref CouchbasePasswordSecret
    Export:
      Name: CouchbasePasswordSecretARN
  MongoUriSecret:
    Description: Mongo URI secret ID
    Value: !Ref MongoUriSecret
    Export:
      Name: MongoUriSecretARN
