###### Default properties ######
spring:
  application:
    name: "@project.name@"
  banner:
    # https://www.ascii-art-generator.org/
    location: classpath:/api-banner.txt
  data:
    mongodb:
      uri: mongodb://camila:camila@localhost:27017/camila-db
      authentication-database: camila-db
      ssl:
        enabled: false
      auto-index-creation: true
      uuid-representation: java_legacy
  webflux:
    base-path: /product-dev/api
  config:
    import: "optional:configserver:"
    #import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      enabled: true
      retry:
        max-attempts: 10
        max-interval: 10000
        initial-interval: 1000
        multiplier: 1.1
      discovery:
        enabled: true
        service-id: "camila-config"
      label: main
      profile: ${ACTIVE_SPRING_PROFILE}
      name: ${spring.application.name}
      allow-override: true

info:
  app:
    name: "@project.name@"
    version: "@project.version@"

springdoc:
  swagger-ui:
    filter: true
    show-common-extensions: true
    doc-expansion: none
    operations-sorter: method
    persist-authorization: true
    deep-linking: true
    display-request-duration: true
    defaultModelsExpandDepth: 1
    tagsSorter: alpha
  show-actuator: true
  api-docs:
    enabled: true
    groups:
      enabled: true
    resolve-schema-properties: true
  show-login-endpoint: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
      show-values: always
      cache:
        time-to-live: 60s
    info:
      enabled: true
      cache:
        time-to-live: 3600s
    beans:
      enabled: true
      cache:
        time-to-live: 10s
    health:
      enabled: true
      show-details: always
      show-components: always
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full

logging:
  charset:
    file: UTF-8
    console: UTF-8
  config: classpath:logback.xml

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.8

server:
  port: ${PORT:8080}

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${spring.webflux.base-path}/actuator/info
    healthCheckUrlPath: ${spring.webflux.base-path}/actuator/health
    nonSecurePortEnabled: true
    leaseRenewalIntervalInSeconds: 15

---
spring:
  main:
    log-startup-info: false
  config:
    activate:
      on-profile: "loc | dev"

logging:
  level:
    org.springframework.boot: debug
    org.springframework: debug
    org.springframework.data: debug

---
###### Integration properties ######
spring:
  main:
    log-startup-info: false
  config:
    activate:
      on-profile: "int"
  webflux:
    base-path: /product-int/api
  data:
    mongodb:
      uri: mongodb://camilauser:camilauser@mongo-nodeport-svc.mongodb.svc.cluster.local:27017/camila-db
      authentication-database: camila-db

---
###### Production properties ######

# Spring base properties
spring:
  main:
    log-startup-info: false
  config:
    activate:
      on-profile: "pro"
  webflux:
    base-path: /product-pro/api
  devtools:
    add-properties: false
    livereload:
      enabled: false

# Turn off global debug
debug: false

logging:
  level:
    org.hibernate.validator: error
    org.springframework: error
    org.springframework.web: error
    org.springframework.data: error
    org.springframework.boot.web.embedded.netty: info
