###### Default properties ######
spring:
  application:
    name: "@project.name@"
  banner:
    # https://www.ascii-art-generator.org/
    location: classpath:/api-banner.txt
  cloud:
    refresh:
      # https://github.com/spring-cloud/spring-cloud-release/wiki/AOT-transformations-and-native-image-support#refresh-scope
      enabled: false
  couchbase:
    connection-string: couchbase://localhost:11207
    username: Administrator
    password: password
    env:
      ssl:
        enabled: false
  data:
    couchbase:
      bucket-name: camila-product-bucket
      scope-name: product
    mongodb:
      # https://www.mongodb.com/docs/manual/tutorial/connection-pool-performance-tuning/
      uri: "mongodb://camilauser:camilauser@localhost:27017/camila-db?maxPoolSize=200&connectTimeoutMS=120000&timeoutMS=120000&serverSelectionTimeoutMS=90000"
      authentication-database: camila-db
      ssl:
        enabled: false
      auto-index-creation: true
      uuid-representation: JAVA_LEGACY
  docker:
    compose:
      enabled: false
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  main:
    web-application-type: reactive
  rsocket:
    server:
      mapping-path: /product-dev/api/rsocket
      transport: websocket
  webflux:
    base-path: /product-dev/api
  cache:
    type: caffeine
    cache-names: findByInternalId,sortedProducts
    caffeine:
      spec: initialCapacity=100,maximumSize=10000,expireAfterAccess=60s

info:
  app:
    name: "@project.name@"
    version: "@project.version@"

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
    resolve-schema-properties: true
  enable-spring-security: false
  show-actuator: true
  show-login-endpoint: true
  swagger-ui:
    filter: true
    show-extensions: true
    show-common-extensions: true
    doc-expansion: none
    operations-sorter: method
    persist-authorization: true
    deep-linking: true
    display-request-duration: true
    display-operation-id: true
    defaultModelsExpandDepth: 1
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
      cache:
        time-to-live: 60s
      access: unrestricted
    info:
      cache:
        time-to-live: 3600s
      access: unrestricted
    beans:
      cache:
        time-to-live: 10s
      access: unrestricted
    health:
      show-details: ALWAYS
      show-components: ALWAYS
      access: unrestricted
    configprops:
      show-values: ALWAYS
      access: unrestricted
    shutdown:
      access: unrestricted
    prometheus:
      access: unrestricted
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    os:
      enabled: true
    process:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
  tracing:
    enabled: false

logging:
  charset:
    console: UTF-8
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: "${info.app.name}"
        version: "${info.app.version}"
        environment: "${spring.profiles.active}"
  level:
    root: INFO
    com.camila.api.product: DEBUG
    com.camila.api.product.infrastructure.adapter.output.mongo.config.MongoCondition: ERROR
    com.camila.api.product.infrastructure.adapter.output.couchbase.config.CouchbaseCondition: ERROR
    org.springframework: INFO
    org.springframework.web: WARN
    org.springframework.data: WARN
    org.springframework.context: WARN
    org.mongodb: WARN
    com.mongodb: WARN
    com.couchbase: WARN
    org.springframework.boot: INFO
    org.springframework.boot.web.embedded.netty: WARN
    net.devh.boot.grpc.server: WARN
    io.grpc.netty: WARN
    reactor: WARN

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.5

server:
  port: ${PORT:8080}
  shutdown: immediate

grpc:
  # this client only is util to testing
  client:
    product-service:
      address: static://localhost:6565
    GLOBAL:
      negotiation-type: plaintext
  server:
    port: 0 # by default random port
    shutdown-grace-period: 0
    health-service-enabled: true
    reflection-service-enabled: true

repository:
  technology: ${REPOSITORY_TECHNOLOGY:mongo}

---
###### Local|Dev properties ######
spring:
  config:
    activate:
      on-profile: "loc|dev"
  jmx:
    enabled: true
  rsocket:
    server:
      port: 7000

grpc:
  server:
    port: 6565

management:
  endpoint:
    chaosmonkey:
      access: unrestricted
    chaosmonkeyjmx:
      access: unrestricted

# https://github.com/codecentric/chaos-monkey-spring-boot/tree/main/chaos-monkey-docs/src/main/asciidoc
chaos:
  monkey:
    enabled: true
    watcher:
      rest-controller: true
      service: true
      repository: true
      component: false
      actuator-health: true
      controller: false
      rest-template: false
      web-client: false
    assaults:
      level: 10
      latency-active: true
      exceptions-active: true
      kill-application-active: true
      memory-active: true
      cpu-active: true

debug: false
logging:
  level:
    root: ERROR
    com.camila.api.product: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    org.springframework.security: ERROR
    org.springframework.security.oauth2: ERROR
    org.springframework.web.reactive.socket: ERROR
    org.springframework.context: ERROR
    org.mongodb: ERROR
    com.mongodb: ERROR
    com.couchbase: ERROR
    org.springframework.boot: ERROR
    org.springframework.boot.web.embedded.netty: ERROR
    net.devh.boot.grpc.server: ERROR
    io.grpc.netty: ERROR
    reactor: ERROR
    org.hibernate.validator: ERROR
    com.netflix.discovery: ERROR

---
###### Disable config|discovery feature by default ######
spring:
  config:
    activate:
      on-profile: "!dev"
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  security:
    user:
      name: camila
      password: camila

---
###### Enable config|discovery feature on remote deploy ######
spring:
  config:
    activate:
      on-profile: "dev"
    import: "optional:configserver:${CONFIG_SERVER_URI:}"
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
      retry:
        max-attempts: 10
        max-interval: 10000
        initial-interval: 1000
        multiplier: 1.1
      discovery:
        enabled: true
        service-id: "camila-config"
      label: main
      profile: ${SPRING_PROFILES_ACTIVE:dev}
      name: ${spring.application.name}
      allow-override: true
  # Enable keycloak security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${KEYCLOAK_URL:http://localhost:9191}/realms/${KEYCLOAK_REALM:camila-realm}"

springdoc:
  enable-spring-security: true
  show-oauth2-endpoints: true

# Enable keycloak security
openapi:
  oAuthFlow:
    url: "${GATEWAY_SERVER_URL:http://localhost}:${server.port:8080}"
    tokenUrl: "${KEYCLOAK_URL:http://localhost:9191}/realms/${KEYCLOAK_REALM:camila-realm}/protocol/openid-connect/token"
    authorizationUrl: "${KEYCLOAK_URL:http://localhost:9191}/realms/${KEYCLOAK_REALM:camila-realm}/protocol/openid-connect/auth"
    refreshUrl: "${KEYCLOAK_URL:http://localhost:9191}/realms/${KEYCLOAK_REALM:camila-realm}/protocol/openid-connect/token"

# Enable Eureka client
eureka:
  client:
    enabled: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${HOSTNAME}:${spring.application.name}:${server.port}:${random.int(0,9)}
    statusPageUrlPath: ${spring.webflux.base-path}/actuator/info
    healthCheckUrlPath: ${spring.webflux.base-path}/actuator/health
    async-client-initialization: true
    nonSecurePortEnabled: true
    non-secure-port: ${server.port}
    metadata-map:
      weight: ${random.int(1,10)}
      startup: ${random.int}
      # https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/1.3.6.RELEASE/multi/multi__service_discovery_eureka_clients.html#_status_page_and_health_indicator
      management.context-path: ${spring.webflux.base-path}/actuator
    leaseExpirationDurationInSeconds: 30
    leaseRenewalIntervalInSeconds: 15

# Enable all management endpoints
# https://docs.spring.io/spring-boot/reference/actuator/tracing.html#actuator.micrometer-tracing.tracer-implementations
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
      connect-timeout: 10s
      read-timeout: 30s

---
###### Integration properties ######
spring:
  config:
    activate:
      on-profile: "int"
  data:
    mongodb:
      uri: "mongodb://camilauser:camilauser@mongo-nodeport-svc.mongodb.svc.cluster.local:27017/camila-db?maxPoolSize=200&connectTimeoutMS=30000&timeoutMS=120000"
      authentication-database: camila-db
  rsocket:
    server:
      mapping-path: /product-int/api/rsocket
      transport: websocket
      port: 7000
  webflux:
    base-path: /product-int/api

grpc:
  server:
    port: 6565

# Disable all management endpoints
management:
  tracing:
    enabled: false

---
###### Production properties ######

# Spring base properties
spring:
  config:
    activate:
      on-profile: "pre|pro"
  devtools:
    add-properties: false
    livereload:
      enabled: false
  main:
    log-startup-info: true
  rsocket:
    server:
      mapping-path: /product/api/rsocket
      port: 7000
  webflux:
    base-path: /product/api

  # Enable AWS Cognito Oauth2 security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${SECURITY_ISSUER_URI}"

# Set GRPC port
grpc:
  server:
    port: 6565

# Disable all management endpoints
management:
  tracing:
    enabled: false

# Turn off global forward headers
server:
  forward-headers-strategy: framework

# Turn off global debug
debug: false

# Enable OpenApi
openapi:
  oAuthFlow:
    url: "${SERVER_URL:http://localhost:8080}"
    tokenUrl: "${SECURITY_DOMAIN_URI}/oauth2/token"
    authorizationUrl: "${SECURITY_DOMAIN_URI}/oauth2/authorize"
    refreshUrl: "${SECURITY_DOMAIN_URI}/oauth2/token"

# Enable logging for all levels
logging:
  level:
    reactor: ERROR
    org.hibernate.validator: ERROR
    org.springframework: ERROR
    org.springframework.web: ERROR
    org.springframework.data: ERROR
    org.springframework.context: ERROR
    org.mongodb: ERROR
    com.mongodb: ERROR
    com.couchbase: ERROR
    org.springframework.boot: ERROR
    org.springframework.boot.web.embedded.netty: INFO
    net.devh.boot.grpc.server: ERROR
    io.grpc.netty: ERROR

---
###### Local docker compose properties ######

spring:
  config:
    activate:
      on-profile: "local-compose"
  couchbase:
    connection-string: couchbase
  data:
    mongodb:
      uri: "mongodb://camilauser:camilauser@mongodb:27017/camila-db?maxPoolSize=200&connectTimeoutMS=120000&timeoutMS=120000&serverSelectionTimeoutMS=90000"
      auto-index-creation: true
      uuid-representation: JAVA_LEGACY
      ssl:
        enabled: false
  # https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.docker-compose
  docker:
    compose:
      enabled: true
      skip:
        in-tests: true
      start:
        command: up
        skip: if_running
        log-level: debug
      stop:
        command: down
        timeout: 15s
      readiness:
        timeout: 2m
        wait: only_if_started
      profiles:
        active: "docker-compose"
      file: "${user.dir}/../camila-orchestrator/dev/compose/docker-compose-spring-boot.yml"
      lifecycle-management: start_and_stop
  jmx:
    enabled: true
  rsocket:
    server:
      port: 7000

grpc:
  server:
    port: 6565

debug: false
logging:
  level:
    root: INFO
    com.camila.api: DEBUG
    com.camila.api.product.infrastructure.adapter.output.mongo.config.MongoCondition: ERROR
    com.camila.api.product.infrastructure.adapter.output.couchbase.config.CouchbaseCondition: ERROR
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.data: WARN
    org.springframework.context: WARN
    org.mongodb: WARN
    com.mongodb: WARN
    com.couchbase: WARN
    org.springframework.boot: WARN
    org.springframework.boot.actuate: WARN
    org.springframework.boot.docker: WARN
    org.springframework.boot.rsocket: WARN
    net.devh.boot.grpc.server: WARN
    io.grpc.netty: WARN
    io.netty: WARN
    reactor: WARN
