spring:
  application:
    name: "@project.name@"
  banner:
    # https://www.ascii-art-generator.org/
    location: classpath:/discovery-banner.txt
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:loc}

info:
  app:
    name: "@project.name@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: ALWAYS
      cache:
        time-to-live: 60s
      access: unrestricted
    info:
      cache:
        time-to-live: 3600s
      access: unrestricted
    beans:
      cache:
        time-to-live: 10s
      access: unrestricted
    health:
      show-details: ALWAYS
      show-components: ALWAYS
      access: unrestricted
    configprops:
      show-values: ALWAYS
      access: unrestricted
    shutdown:
      access: unrestricted
    prometheus:
      access: unrestricted
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full

server:
  port: ${PORT:8761}
  forward-headers-strategy: framework

eureka:
  client:
    # commented to registry itself in admin dashboard
    #registerWithEureka: false
    #fetchRegistry: false
    enabled: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: actuator/info
    healthCheckUrlPath: actuator/health
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${random.value}
    nonSecurePortEnabled: true
    leaseRenewalIntervalInSeconds: 15

logging:
  level:
    org.springframework.boot: DEBUG
    org.springframework: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
