kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
kubeadmConfigPatchesJSON6902:
  - group: kubeadm.k8s.io
    version: v1beta3
    kind: ClusterConfiguration
    patch: |
     - op: add
       path: /apiServer/certSANs/-
       value: my-hostname
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./kind-pvc-hostpath.yml
        containerPath: /kind/manifests/default-storage.yaml
      - hostPath: /tmp/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
      - hostPath: /tmp/shared
        containerPath: /tmp/shared
      - hostPath: /tmp/kind/_default
        containerPath: /etc/containerd/certs.d/_default
    extraPortMappings:
      # knative
      - containerPort: 31080
        hostPort: 80
      - containerPort: 31443
        hostPort: 443
      # Para exponer api rest/graphql/websocket
      - containerPort: 30080
        hostPort: 8080
      - containerPort: 30005
        hostPort: 5005
      # Para exponer rsocket
      - containerPort: 30070
        hostPort: 7000
      # Para exponer api grpc
      - containerPort: 30065
        hostPort: 6565
      # Para exponer mongo
      - containerPort: 32000
        hostPort: 27017
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
  - role: worker
    extraMounts:
      - hostPath: /tmp/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
      - hostPath: /tmp/shared
        containerPath: /tmp/shared
      - hostPath: /tmp/kind/_default
        containerPath: /etc/containerd/certs.d/_default
    labels:
      tier: utils
  - role: worker
    extraMounts:
      - hostPath: /tmp/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
      - hostPath: /tmp/shared
        containerPath: /tmp/shared
      - hostPath: /tmp/kind/_default
        containerPath: /etc/containerd/certs.d/_default
    labels:
      tier: backend
  - role: worker
    extraMounts:
      - hostPath: /tmp/hostpath-provisioner
        containerPath: /tmp/hostpath-provisioner
      - hostPath: /tmp/shared
        containerPath: /tmp/shared
      - hostPath: /tmp/kind/_default
        containerPath: /etc/containerd/certs.d/_default
    labels:
      tier: backend
