---
apiVersion: v1
kind: Namespace
metadata:
  name: camila-product-api-serveless-ns
spec: {}
status: {}

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: camila-product-api-serveless-ns-quota
  namespace: camila-product-api-serveless-ns
spec:
  hard:
    limits.cpu: "8"
    limits.memory: 8192Mi
    pods: "10"
    requests.cpu: "8"
    requests.memory: 8192Mi

---
apiVersion: v1
kind: Secret
metadata:
  name: camila-product-api-serveless-creds
  namespace: camila-product-api-serveless-ns
data:
  uri: "bW9uZ29kYjovL2NhbWlsYXVzZXI6Y2FtaWxhdXNlckBtb25nby1ub2RlcG9ydC1zdmMubW9uZ29kYi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9jYW1pbGEtZGI="
  #mongodb://camilauser:camilauser@mongo-nodeport-svc.mongodb.svc.cluster.local:27017/camila-db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: camila-product-api-serveless-config
  namespace: camila-product-api-serveless-ns
data:
  SPRING_PROFILES_ACTIVE: "int"
  REPOSITORY_TECHNOLOGY: "mongo"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: camila-product-api-serveless
  namespace: camila-product-api-serveless-ns
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "20"
        serving.knative.dev/progress-deadline: "10s"
    spec:
      containers:
        - image: docker.io/library/camila-product-api-serveless:1.0.0
          name: camila-product-api-serveless
          imagePullPolicy: Never
          ports:
            - containerPort: 31080
          resources:
            limits:
              cpu: "2"
              memory: 1024Mi
            requests:
              cpu: "1"
              memory: 512Mi
          env:
            - name: spring.data.mongodb.uri
              valueFrom:
                secretKeyRef:
                  name: camila-product-api-serveless-creds
                  key: uri
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: camila-product-api-serveless-config
                  key: SPRING_PROFILES_ACTIVE
