### Rest - Actuator
# https://tech.jpje.xyz/product/api/swagger-ui.html
#GET https://jpje.net/actuator/health
GET {{apiProtocol}}{{apiHost}}:{{apiPort}}{{apiPath}}/actuator/health HTTP/2
Accept: application/json
Content-Type: application/json

### Rest - findById (SSE)
# https://tech.jpje.xyz/product/api/swagger-ui.html
#GET https://jpje.net/products/99999 HTTP/2
GET {{apiProtocol}}{{apiHost}}:{{apiPort}}{{apiPath}}/products/63255 HTTP/2
Accept: text/event-stream
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Rest - sortProducts (ndjson)
# https://tech.jpje.xyz/product/api/swagger-ui.html
#GET https://jpje.net/products?salesUnits=0.001&stock=0.999&page=0&size=10 HTTP/2
GET {{apiProtocol}}{{apiHost}}:{{apiPort}}{{apiPath}}/products?salesUnits=0.001&stock=0.999&page=0&size=100 HTTP/2
Accept: application/x-ndjson
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Graphql - findById
#GRAPHQL https://jpje.net/graphql
GRAPHQL {{apiProtocol}}{{apiHost}}:{{apiPort}}{{apiPath}}/graphql
Authorization: Bearer {{$auth.token("auth-id")}}

query findById($internalId: ID) {
  findById(internalId: $internalId) {
    id, internalId, category, name, salesUnits, stock
  }
}

{
"internalId": "88888"
}

### Graphql - sortProducts
#GRAPHQL https://jpje.net/graphql
GRAPHQL {{apiProtocol}}{{apiHost}}:{{apiPort}}{{apiPath}}/graphql
Authorization: Bearer {{$auth.token("auth-id")}}

query sortProducts($salesUnits: Float, $stock: Float, $page: Int, $size: Int, $withDetails: Boolean!) {
  sortProducts(salesUnits: $salesUnits, stock: $stock, page: $page, size: $size) {
    id @include(if: $withDetails)
    internalId @include(if: $withDetails)
    category @include(if: $withDetails)
    name
    salesUnits
    stock
  }
}

{
  "salesUnits": 0.00001,
  "stock": 0.00001,
  "profitMargin": 0.00008,
  "daysInStock": 0.99990,
  "page": 0,
  "size": 1000,
  "withDetails": false
}

### Websockt
WEBSOCKET {{apiSocketProtocol}}{{apiHost}}:{{apiPort}}{{apiPath}}/ws/products
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

===
{
  "method": "FIND_BY_INTERNAL_ID",
  "internalId": "100000"
}
=== wait-for-server
{
  "method": "SORT_PRODUCTS",
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "10000"
}
=== wait-for-server

### RSocket request rsponse with websocket - findByInternalId
RSOCKET products.request-response-findByInternalId
Host: {{apiSocketProtocol}}{{apiHost}}:7001{{apiPath}}/rsocket
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "internalId": "5"
}

### RSocket request stream with websocket - SortProducts
RSOCKET products.request-stream-sortByMetricsWeights
Host: {{apiSocketProtocol}}{{apiHost}}:7001{{apiPath}}/rsocket
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "5"
}

### GRPC - findByInternalId
GRPC {{apiGrpcProtocol}}{{apiHost}}:50051/product.ProductService/GetProductByInternalId

{
  "internalId": "1000"
}

### GRPC - SortProducts
GRPC {{apiGrpcProtocol}}{{apiHost}}:50051/product.ProductService/SortByMetricsWeights

{
  "requestParams": {
    "salesUnits": "0.999",
    "stock": "0.001",
    "page": "0",
    "size": "1000"
  }
}
