### Rest - Actuator
# http://poc.jpje-kops.xyz/product/api/swagger-ui.html
GET https://poc.jpje-kops.xyz/product/api/actuator/health HTTP/2
Accept: application/json
Content-Type: application/json

### Rest - findById (SSE)
# http://poc.jpje-kops.xyz/product/api/swagger-ui.html
GET https://poc.jpje-kops.xyz/product/api/products/99999 HTTP/2
Accept: text/event-stream
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Rest - sortProducts (ndjson)
# http://poc.jpje-kops.xyz/product/api/swagger-ui.html
GET https://poc.jpje-kops.xyz/product/api/products?salesUnits=0.001&stock=0.999&page=0&size=10 HTTP/2
Accept: application/x-ndjson
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

### Graphql - findById
GRAPHQL https://poc.jpje-kops.xyz/product/api/graphql
Authorization: Bearer {{$auth.token("auth-id")}}

query findById($internalId: ID) {
  findById(internalId: $internalId) {
    id, internalId, category, name, salesUnits, stock
  }
}

{
"internalId": "88888"
}

### Graphql - sortProducts
GRAPHQL https://poc.jpje-kops.xyz/product/api/graphql
Authorization: Bearer {{$auth.token("auth-id")}}

query sortProducts($salesUnits: Float, $stock: Float, $page: Int, $size: Int, $withDetails: Boolean!) {
  sortProducts(salesUnits: $salesUnits, stock: $stock, page: $page, size: $size) {
    id @include(if: $withDetails)
    internalId @include(if: $withDetails)
    category @include(if: $withDetails)
    name
    salesUnits
    stock
  }
}

{
  "salesUnits": 0.999,
  "stock": 0.001,
  "page": 0,
  "size": 1000,
  "withDetails": false
}

### Websockt
WEBSOCKET ws://poc.jpje-kops.xyz/product/api/ws/products
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

===
{
  "method": "FIND_BY_INTERNAL_ID",
  "internalId": "100000"
}
=== wait-for-server
{
  "method": "SORT_PRODUCTS",
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "5"
}
=== wait-for-server

### RSocket request rsponse with websocket - findByInternalId
RSOCKET products.request-response-findByInternalId
Host: ws://poc.jpje-kops.xyz:7443/rsocket
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "internalId": "5"
}

### RSocket request stream with websocket - SortProducts
RSOCKET products.request-stream-sortByMetricsWeights
Host: ws://poc.jpje-kops.xyz:7443/rsocket
Content-Type: text/event-stream
Authorization: Bearer {{$auth.token("auth-id")}}

{
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "5"
}
