spring:
  application:
    name: "@project.name@"
  banner:
    # https://www.ascii-art-generator.org/
    location: classpath:/config-banner.txt
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE:loc}
      - native
  main:
    web-application-type: servlet
    lazy-initialization: true
  config:
    name: ${spring.application.name}
  cloud:
    config:
      name: ${spring.application.name}
      server:
        native:
          search-locations: classpath:/config-server, file:./config-server
        #git:
        #  uri: ${CONFIG_REPO_URI:https://github.com/JuanPabloJimenezEsclusa/camila-services.git}
        #  delete-untracked-branches: true
        #  timeout: 10
        #  default-label: main
        #  basedir: ./camila-config/src/main/resources/config-server/

info:
  app:
    name: "@project.name@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
      show-values: always
      cache:
        time-to-live: 60s
    info:
      enabled: true
      cache:
        time-to-live: 3600s
    beans:
      enabled: true
      cache:
        time-to-live: 10s
    health:
      enabled: true
      show-details: always
      show-components: always
    configprops:
      enabled: true
      show-values: always
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
      connect-timeout: 10s
      read-timeout: 30s

server:
  port: ${PORT:8888}
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.boot: debug
    org.springframework: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    statusPageUrlPath: actuator/info
    healthCheckUrlPath: actuator/health
    nonSecurePortEnabled: true
    leaseRenewalIntervalInSeconds: 15
