### Rest - Actuator
GET https://tech.jpje.xyz/product-int/api/actuator/health/readiness HTTP/2
Accept: application/json
Content-Type: application/json

### Rest - Actuator - MongoDB
GET https://tech.jpje.xyz/product-int/api/actuator/health/mongo HTTP/2
Accept: application/json
Content-Type: application/json

### Rest - Actuator - Couchbase
GET https://tech.jpje.xyz/product-int/api/actuator/health/couchbase HTTP/2
Accept: application/json
Content-Type: application/json

### Rest - findById (SSE)
GET https://tech.jpje.xyz/product-int/api/products/99999 HTTP/2
Accept: text/event-stream
Content-Type: application/json

### Rest - sortProducts (ndjson)
GET https://tech.jpje.xyz/product-int/api/products?salesUnits=0.999&stock=0.001&page=0&size=100 HTTP/2
Accept: application/x-ndjson
Content-Type: application/json

### Graphql - findById
GRAPHQL https://tech.jpje.xyz/product-int/api/graphql

query findById($internalId: ID) {
  findById(internalId: $internalId) {
    id, internalId, category, name, salesUnits, stock
  }
}

{
"internalId": "88888"
}

### Graphql - sortProducts
GRAPHQL https://tech.jpje.xyz/product-int/api/graphql

query sortProducts($salesUnits: Float, $stock: Float, $page: Int, $size: Int, $withDetails: Boolean!) {
  sortProducts(salesUnits: $salesUnits, stock: $stock, page: $page, size: $size) {
    id @include(if: $withDetails)
    internalId @include(if: $withDetails)
    category @include(if: $withDetails)
    name
    salesUnits
    stock
  }
}

{
  "salesUnits": 0.001,
  "stock": 0.999,
  "page": 0,
  "size": 1000,
  "withDetails": false
}

### Websockt
WEBSOCKET wss://tech.jpje.xyz/product-int/api/ws/products
Content-Type: application/json

===
{
  "method": "SORT_PRODUCTS",
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "10000"
}
=== wait-for-server

### RSocket request rsponse with websocket - findByInternalId
RSOCKET products.request-response-findByInternalId
Host: wss://tech.jpje.xyz/product-int/api/rsocket

{
  "internalId": "5"
}

### RSocket request stream with websocket - SortProducts
RSOCKET products.request-stream-sortByMetricsWeights
Host: wss://tech.jpje.xyz/product-int/api/rsocket

{
  "salesUnits": "0.001",
  "stock": "0.999",
  "page": "0",
  "size": "5"
}

### GRPC - findByInternalId
GRPC grpcs://tech.jpje.xyz/product.ProductService/GetProductByInternalId

{
  "internalId": "1000"
}

### GRPC - SortProducts
GRPC grpcs://tech.jpje.xyz/product.ProductService/SortByMetricsWeights

{
  "requestParams": {
    "salesUnits": "0.999",
    "stock": "0.001",
    "page": "0",
    "size": "1000"
  }
}
