plugins {
  id 'java'
  id 'org.springframework.boot'
  id 'io.spring.dependency-management'
}

description = 'Camila Product API - Couchbase Output Adapter'

dependencies {
  // Internal Modules
  implementation project(':camila-product-api-domain')
  implementation project(':camila-product-api-application')

  // Spring Boot Data
  implementation 'org.springframework.boot:spring-boot-starter-data-couchbase'
  implementation 'org.springframework.boot:spring-boot-starter-data-couchbase-reactive'
  implementation "com.couchbase.client:java-client:${couchbaseJavaClient}"

  // Utilities
  compileOnly 'org.jspecify:jspecify'

  // Development Tools
  compileOnly 'org.projectlombok:lombok'
  annotationProcessor 'org.projectlombok:lombok'
  annotationProcessor "org.mapstruct:mapstruct-processor:${mapstruct}"
  implementation "org.mapstruct:mapstruct:${mapstruct}"

  // Testing
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'io.projectreactor:reactor-test'
  testImplementation 'org.testcontainers:testcontainers'
  testImplementation 'org.testcontainers:testcontainers-couchbase'
}
