---
apiVersion: v1
kind: Namespace
metadata:
  name: test
spec: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smoke-test-account
  namespace: test

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-e03ceee8-6c38-4288-97f1-9b682ba87d6e
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test
    namespace: test
  hostPath:
    path: /tmp/hostpath-provisioner/pvc-e03ceee8-6c38-4288-97f1-9b682ba87d6e
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  namespace: test
spec:
  serviceName: test
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: "smoke-test-account"
      automountServiceAccountToken: false
      containers:
      - name: name
        image: nginx:stable
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
            ephemeral-storage: "1Gi"
          requests:
            cpu: "0.5"
            memory: 256Mi
            ephemeral-storage: "500Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volume
          mountPath: /pvc/
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: test

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: test
  labels:
    app: test
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
