---
apiVersion: v1
kind: Namespace
metadata:
  name: camila-product-api-serveless-ns
spec: {}
status: {}

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: camila-product-api-serveless-ns-quota
  namespace: camila-product-api-serveless-ns
spec:
  hard: 
    limits.cpu: "8"
    limits.memory: 8192Mi
    pods: "10"
    requests.cpu: "8"
    requests.memory: 8192Mi

---
apiVersion: v1
kind: Secret
metadata:
  name: camila-product-api-serveless-creds
  namespace: camila-product-api-serveless-ns
data:
  uri: "bW9uZ29kYjovL3phcmF1c2VyOnphcmF1c2VyQG1vbmdvLW5vZGVwb3J0LXN2Yy5tb25nb2RiLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L3phcmEtZGI="
  #mongodb://camilauser:camilauser@mongo-nodeport-svc.mongodb.svc.cluster.local:27017/camila-db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: camila-product-api-serveless-config
  namespace: camila-product-api-serveless-ns
data:
  SPRING_PROFILES_ACTIVE: "int"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: camila-product-api-serveless
  namespace: camila-product-api-serveless-ns
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "20"
    spec:
      containers:
      - image: docker.io/library/camila-product-api-serveless:1.0.0
        name: camila-product-api-serveless
        imagePullPolicy: Never
        ports:
        - containerPort: 31080
        resources:
          limits:
            cpu: "2"
            memory: 1024Mi
          requests:
            cpu: "1"
            memory: 512Mi
        env:
        - name: spring.data.mongodb.uri
          valueFrom:
            secretKeyRef:
              name: camila-product-api-serveless-creds
              key: uri
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: camila-product-api-serveless-config
              key: SPRING_PROFILES_ACTIVE
