# This workflow uses actions that are not certified by GitHub.
# Build by: Juan Pablo Jimenez
# 2024-06-04

name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_PRODUCT: camila-product-api:1.0.0
  IMAGE_CONFIG: camila-config:1.0.0
  IMAGE_DISCOVERY: camila-discovery:1.0.0
  IMAGE_GATEWAY: camila-gateway:1.0.0
  IMAGE_ADMIN: camila-admin:1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        run: | 
          mvn -B spring-boot:build-image -Dmaven.test.skip=true -f pom.xml

      - name: Transform lowercase - github.repository_owner
        run: |
          echo "REPOSITORY_OWNER=`echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: Tag images
        run: |
          docker tag ${{ env.IMAGE_PRODUCT }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_PRODUCT }}
          docker tag ${{ env.IMAGE_CONFIG }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_CONFIG }}
          docker tag ${{ env.IMAGE_DISCOVERY }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_DISCOVERY }}
          docker tag ${{ env.IMAGE_GATEWAY }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_GATEWAY }}
          docker tag ${{ env.IMAGE_ADMIN }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_ADMIN }}

      - name: Smoke Tests
        run: |
          docker images

      - name: Push image to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_PRODUCT }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_CONFIG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_DISCOVERY }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_GATEWAY }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_ADMIN }}
