name: Docker Publish

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_PRODUCT: camila-product-api:1.0.0
  IMAGE_GATEWAY: camila-gateway:1.0.0
  IMAGE_ADMIN: camila-admin:1.0.0

jobs:
  deploy:
    if: github.event.pull_request.draft == false
    name: Build and Publish Docker Images
    environment: pro
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Configure GPG Key
        run: |
          echo -n "${MAVEN_GPG_KEY}" | base64 --decode | gpg --batch --passphrase ${MAVEN_GPG_PASSPHRASE} --import
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Set up Docker Buildx
        # git ls-remote --tags https://github.com/docker/setup-buildx-action.git
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c
      - name: Log into registry ${{ env.REGISTRY }}
        # git ls-remote --tags https://github.com/docker/login-action.git
        uses: docker/login-action@371161bbe7024a29a25c5e19bfcbc0804fe9ad2c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: |
          mvn -B install spring-boot:build-image \
            -Dmaven.test.skip=true \
            -Dmaven.build.cache.enabled=false
        env:
          MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Transform lowercase - github.repository_owner
        run: |
          echo "REPOSITORY_OWNER=`echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Tag images
        run: |
          docker tag ${{ env.IMAGE_PRODUCT }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_PRODUCT }}
          docker tag ${{ env.IMAGE_GATEWAY }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_GATEWAY }}
          docker tag ${{ env.IMAGE_ADMIN }} ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_ADMIN }}
      - name: Smoke Tests
        run: |
          docker images
      - name: Push image to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_PRODUCT }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_GATEWAY }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_ADMIN }}
